<?php

namespace AppBundle\Repository;

/**
 * CorrectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorrectionRepository extends \Doctrine\ORM\EntityRepository
{
}
