<?php

namespace AppBundle\Repository;

/**
 * ProofreaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProofreaderRepository extends \Doctrine\ORM\EntityRepository
{
}
